default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: 1234
  host: db
  port: 5432

development:
  <<: *default
  database: uncampusconnect_tutorprofile_db

test:
  <<: *default
  database: uncampusconnect_tutorprofile_db_test

production:
  <<: *default
  database: uncampusconnect_tutorprofile_db_production
  username: uncampusconnect_tutorprofile_db
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
